# E-Commerce Data CleaningStep-by-step cleaning process: load data -> explore -> fix data types -> handle missing values column by column -> final check.

## 1. Import Libraries

In [1]:
import pandas as pd

## 2. Load Dataset

In [2]:
ecommerce = pd.read_csv("/content/ecommerce.csv")
ecommerce

,Order_ID,Order_Date,Customer_ID,Product_Name,Category,Sub_Category,Quantity,Sales,Discount,Profit,City,State,Payment_Mode
0,ORD13379,01/01/2025,CUST03038,T-Shirt,Clothing,Men,1.0,845.00,0,61.98,Chennai,Tamil Nadu,UPI
1,ORD31029,01/01/2025,CUST05160,T-Shirt,Clothing,Men,3.0,2428.20,5,341.68,Vijayawada,Andhra Pradesh,Credit Card
2,ORD13421,01/01/2025,CUST05005,Dress,Clothing,Women,3.0,6976.80,5,1066.95,Chennai,Tamil Nadu,Debit Card
3,ORD01988,01/01/2025,CUST06475,Mixer Grinder,Home & Kitchen,Kitchen,4.0,14803.60,15,2723.54,Visakhapatnam,Andhra Pradesh,UPI
4,ORD23309,01/01/2025,CUST05030,Tablet,Electronics,Computers,1.0,19892.00,0,3160.95,Visakhapatnam,Andhra Pradesh,Cash on Delivery
...,...,...,...,...,...,...,...,...,...,...,...,...,...
40195,ORD35711,30/03/2026,CUST05074,Bed Sheet,Home & Kitchen,Home Furnishing,5.0,8320.00,0,1752.95,Bangalore,Karnataka,Credit Card
40196,ORD04082,18/01/2025,CUST01315,Cookware Set,Home & Kitchen,Kitchen,4.0,10796.40,10,1696.22,Mumbai,Maharashtra,Credit Card
40197,ORD13061,15/12/2025,CUST05479,Smart Watch,Electronics,Wearables,5.0,31747.50,10,6441.25,Hyderabad,Telangana,Net Banking
40198,ORD27129,28/05/2026,CUST04318,Smart Watch,Electronics,Wearables,1.0,5088.20,5,843.45,Visakhapatnam,Andhra Pradesh,Cash on Delivery
40199,ORD30647,13/03/2025,CUST00972,Moisturizer,Beauty,Skincare,3.0,1650.15,5,357.92,Pune,Maharashtra,UPI

## 3. Initial Data Exploration

In [3]:
ecommerce.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40200 entries, 0 to 40199
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order_ID      40200 non-null  object
 1   Order_Date    40120 non-null  object
 2   Customer_ID   40120 non-null  object
 3   Product_Name  40200 non-null  object
 4   Category      40120 non-null  object
 5   Sub_Category  40120 non-null  object
 6   Quantity      40120 non-null  float64
 7   Sales         40120 non-null  float64
 8   Discount      40200 non-null  int64
 9   Profit        40120 non-null  float64
 10  City          40120 non-null  object
 11  State         40120 non-null  object
 12  Payment_Mode  40200 non-null  object
dtypes: float64(3), int64(1), object(9)
memory usage: 4.0+ MB

In [4]:
ecommerce.dtypes

Order_ID         object
Order_Date       object
Customer_ID      object
Product_Name     object
Category         object
Sub_Category     object
Quantity        float64
Sales           float64
Discount          int64
Profit          float64
City             object
State            object
Payment_Mode     object
dtype: object

In [5]:
ecommerce.isnull().sum()

Order_ID         0
Order_Date      80
Customer_ID     80
Product_Name     0
Category        80
Sub_Category    80
Quantity        80
Sales           80
Discount         0
Profit          80
City            80
State           80
Payment_Mode     0
dtype: int64

## 4. Clean Order_Date Check missing values, convert to proper datetime format, then fill missing dates with the median date.

In [6]:
ecommerce["Order_Date"].isnull().sum()

np.int64(80)

In [7]:
ecommerce[ecommerce["Order_Date"].isnull()]

,Order_ID,Order_Date,Customer_ID,Product_Name,Category,Sub_Category,Quantity,Sales,Discount,Profit,City,State,Payment_Mode
190,ORD22060,NaN,CUST06139,Face Wash,Beauty,Skincare,5.0,2660.00,5,309.87,Pune,Maharashtra,UPI
371,ORD05586,NaN,CUST01325,T-Shirt,Clothing,Men,3.0,2431.05,5,396.34,Visakhapatnam,Andhra Pradesh,Credit Card
825,ORD25838,NaN,CUST00127,Smartphone,Electronics,Mobiles,1.0,20970.90,10,1755.91,Bangalore,Karnataka,Cash on Delivery
1199,ORD36320,NaN,CUST00026,Shampoo,Beauty,Haircare,4.0,1816.00,0,123.52,Mumbai,Maharashtra,Cash on Delivery
1255,ORD28797,NaN,CUST00221,Cookware Set,Home & Kitchen,Kitchen,4.0,9006.00,5,745.13,Mumbai,Maharashtra,UPI
...,...,...,...,...,...,...,...,...,...,...,...,...,...
37330,ORD06952,NaN,CUST05343,Shoes,Clothing,Footwear,2.0,5977.80,10,882.29,Visakhapatnam,Andhra Pradesh,Cash on Delivery
37447,ORD15153,NaN,CUST02864,Mixer Grinder,Home & Kitchen,Kitchen,5.0,NaN,10,1995.52,Pune,Maharashtra,Credit Card
38899,ORD17629,NaN,CUST02369,Moisturizer,Beauty,Skincare,2.0,1800.00,0,112.22,Mumbai,Maharashtra,Cash on Delivery
39561,ORD36375,NaN,CUST01672,Cookware Set,Home & Kitchen,Kitchen,2.0,5831.10,5,969.95,Visakhapatnam,Andhra Pradesh,Credit Card
39973,ORD06032,NaN,CUST03663,Chair,Home & Kitchen,Furniture,4.0,9450.60,5,1173.58,Mumbai,Maharashtra,Debit Card

In [8]:
ecommerce["Order_Date"] = pd.to_datetime(
    ecommerce["Order_Date"],
    format='%d/%m/%Y'
)
ecommerce["Order_Date"]

0       2025-01-01
1       2025-01-01
2       2025-01-01
3       2025-01-01
4       2025-01-01
           ...
40195   2026-03-30
40196   2025-01-18
40197   2025-12-15
40198   2026-05-28
40199   2025-03-13
Name: Order_Date, Length: 40200, dtype: datetime64[ns]

In [9]:
ecommerce["Order_Date"].median()

Timestamp('2025-10-02 00:00:00')

In [10]:
ecommerce["Order_Date"] = ecommerce["Order_Date"].fillna(ecommerce["Order_Date"].median())
ecommerce["Order_Date"]

0       2025-01-01
1       2025-01-01
2       2025-01-01
3       2025-01-01
4       2025-01-01
           ...
40195   2026-03-30
40196   2025-01-18
40197   2025-12-15
40198   2026-05-28
40199   2025-03-13
Name: Order_Date, Length: 40200, dtype: datetime64[ns]

In [11]:
ecommerce["Order_Date"].isnull().sum()

np.int64(0)

## 5. Clean Category Check missing values and fill with the most frequent value (mode).

In [12]:
ecommerce["Category"].isnull().sum()

np.int64(80)

In [13]:
ecommerce[ecommerce["Category"].isnull()]

,Order_ID,Order_Date,Customer_ID,Product_Name,Category,Sub_Category,Quantity,Sales,Discount,Profit,City,State,Payment_Mode
175,ORD20875,2025-01-03,CUST00375,Hair Dryer,NaN,Haircare,2.0,4080.60,10,400.20,Visakhapatnam,Andhra Pradesh,Debit Card
632,ORD01844,2025-01-10,CUST02795,Jeans,NaN,Men,4.0,6908.80,15,750.80,Chennai,Tamil Nadu,Net Banking
1700,ORD35157,2025-01-24,CUST04195,Jeans,NaN,Men,1.0,1749.00,0,196.02,Pune,Maharashtra,Net Banking
2127,ORD30106,2025-01-29,CUST06404,Jeans,NaN,Men,4.0,6456.20,5,611.53,Bangalore,Karnataka,Debit Card
2187,ORD12011,2025-01-30,CUST06354,Mixer Grinder,NaN,Kitchen,1.0,2851.75,15,208.10,Mumbai,Maharashtra,UPI
...,...,...,...,...,...,...,...,...,...,...,...,...,...
38001,ORD29159,2026-06-03,CUST06434,Moisturizer,NaN,Skincare,3.0,1779.90,15,154.32,Pune,Maharashtra,UPI
38096,ORD39356,2026-06-04,CUST02943,Bed Sheet,NaN,Home Furnishing,2.0,2718.00,10,296.73,Bangalore,Karnataka,Debit Card
39122,ORD17218,2026-06-18,CUST01556,Shampoo,NaN,Haircare,5.0,2376.00,10,296.47,Delhi,Delhi,UPI
39343,ORD31534,2026-06-21,CUST03148,T-Shirt,NaN,Men,3.0,2399.70,5,408.10,Mumbai,Maharashtra,Debit Card
39355,ORD18717,2026-06-21,CUST01426,Smartphone,NaN,Mobiles,2.0,55234.90,5,8205.25,Delhi,Delhi,Debit Card

In [14]:
ecommerce["Category"].mode()

0    Beauty
Name: Category, dtype: object

In [15]:
ecommerce["Category"] = ecommerce["Category"].fillna(ecommerce["Category"].mode()[0])
ecommerce["Category"]

0              Clothing
1              Clothing
2              Clothing
3        Home & Kitchen
4           Electronics
              ...
40195    Home & Kitchen
40196    Home & Kitchen
40197       Electronics
40198       Electronics
40199            Beauty
Name: Category, Length: 40200, dtype: object

In [16]:
ecommerce["Category"].isnull().sum()

np.int64(0)

## 6. Clean Sub_Category Same approach - fill missing values with mode.

In [17]:
ecommerce["Sub_Category"].isnull().sum()

np.int64(80)

In [18]:
ecommerce["Sub_Category"].mode()

0    Skincare
Name: Sub_Category, dtype: object

In [19]:
ecommerce["Sub_Category"] = ecommerce["Sub_Category"].fillna(ecommerce["Sub_Category"].mode()[0])
ecommerce["Sub_Category"]

0                    Men
1                    Men
2                  Women
3                Kitchen
4              Computers
              ...
40195    Home Furnishing
40196            Kitchen
40197          Wearables
40198          Wearables
40199           Skincare
Name: Sub_Category, Length: 40200, dtype: object

In [20]:
ecommerce["Sub_Category"].isnull().sum()

np.int64(0)

## 7. Clean Quantity Numeric column - fill missing values with the mean.

In [21]:
ecommerce["Quantity"].isnull().sum()

np.int64(80)

In [22]:
ecommerce["Quantity"] = ecommerce["Quantity"].fillna(ecommerce["Quantity"].mean())
ecommerce["Quantity"]

0        1.0
1        3.0
2        3.0
3        4.0
4        1.0
        ...
40195    5.0
40196    4.0
40197    5.0
40198    1.0
40199    3.0
Name: Quantity, Length: 40200, dtype: float64

In [23]:
ecommerce["Quantity"].isnull().sum()

np.int64(0)

## 8. Clean Sales Numeric column - fill missing values with the mean.

In [24]:
ecommerce["Sales"].isnull().sum()

np.int64(80)

In [25]:
ecommerce["Sales"].mean()

np.float64(20798.39918619143)

In [26]:
ecommerce["Sales"] = ecommerce["Sales"].fillna(ecommerce["Sales"].mean())
ecommerce["Sales"]

0          845.00
1         2428.20
2         6976.80
3        14803.60
4        19892.00
           ...
40195     8320.00
40196    10796.40
40197    31747.50
40198     5088.20
40199     1650.15
Name: Sales, Length: 40200, dtype: float64

In [27]:
ecommerce["Sales"].isnull().sum()

np.int64(0)

## 9. Clean Profit Numeric column - fill missing values with the mean.

In [28]:
ecommerce["Profit"].isnull().sum()

np.int64(80)

In [29]:
ecommerce[ecommerce["Profit"].isnull()]

,Order_ID,Order_Date,Customer_ID,Product_Name,Category,Sub_Category,Quantity,Sales,Discount,Profit,City,State,Payment_Mode
61,ORD08390,2025-01-01,CUST04855,Tablet,Electronics,Computers,1.0,28307.000000,0,NaN,Hyderabad,Telangana,Debit Card
709,ORD30631,2025-01-11,CUST00534,Bed Sheet,Home & Kitchen,Home Furnishing,4.0,4852.800000,10,NaN,Visakhapatnam,Andhra Pradesh,UPI
1004,ORD20143,2025-01-15,CUST04291,Dress,Clothing,Women,1.0,2085.000000,0,NaN,Pune,Maharashtra,Debit Card
2435,ORD30491,2025-02-03,CUST03351,Perfume,Beauty,Fragrance,4.0,7413.800000,5,NaN,Hyderabad,Telangana,UPI
2695,ORD08218,2025-02-06,CUST05616,T-Shirt,Clothing,Men,4.0,3290.400000,10,NaN,Visakhapatnam,Andhra Pradesh,Credit Card
...,...,...,...,...,...,...,...,...,...,...,...,...,...
38631,ORD26145,2026-06-12,CUST04564,Shoes,Clothing,Footwear,5.0,18819.500000,5,NaN,Bangalore,Karnataka,Cash on Delivery
38656,ORD00590,2026-06-12,CUST00492,Hair Dryer,Beauty,Haircare,5.0,12305.000000,0,NaN,Delhi,Delhi,Debit Card
39365,ORD39618,2026-06-22,CUST03630,Laptop,Electronics,Computers,3.0,127466.250000,5,NaN,Bangalore,Karnataka,Cash on Delivery
39517,ORD08518,2026-06-24,CUST05504,Face Wash,Beauty,Skincare,5.0,20798.399186,0,NaN,Vijayawada,Andhra Pradesh,Credit Card
39976,ORD35116,2026-06-30,CUST03885,Smart Watch,Electronics,Wearables,5.0,29169.000000,10,NaN,Bangalore,Karnataka,Net Banking

In [30]:
ecommerce["Profit"].mean()

np.float64(2920.1032552342967)

In [31]:
ecommerce["Profit"] = ecommerce["Profit"].fillna(ecommerce["Profit"].mean())
ecommerce["Profit"]

0          61.98
1         341.68
2        1066.95
3        2723.54
4        3160.95
          ...
40195    1752.95
40196    1696.22
40197    6441.25
40198     843.45
40199     357.92
Name: Profit, Length: 40200, dtype: float64

In [32]:
ecommerce["Profit"].isnull().sum()

np.int64(0)

## 10. Clean City Categorical column - fill missing values with mode.

In [33]:
ecommerce["City"].isnull().sum()

np.int64(80)

In [34]:
ecommerce["City"].mode()

0    Delhi
Name: City, dtype: object

In [35]:
ecommerce["City"] = ecommerce["City"].fillna(ecommerce["City"].mode()[0])
ecommerce["City"]

0              Chennai
1           Vijayawada
2              Chennai
3        Visakhapatnam
4        Visakhapatnam
             ...
40195        Bangalore
40196           Mumbai
40197        Hyderabad
40198    Visakhapatnam
40199             Pune
Name: City, Length: 40200, dtype: object

In [36]:
ecommerce["City"].isnull().sum()

np.int64(0)

## 11. Clean State Categorical column - fill missing values with mode.

---

In [37]:
ecommerce["State"].isnull().sum()

np.int64(80)

In [38]:
ecommerce["State"].mode()

0    Andhra Pradesh
Name: State, dtype: object

In [39]:
ecommerce["State"] = ecommerce["State"].fillna(ecommerce["State"].mode()[0])
ecommerce["State"]

0            Tamil Nadu
1        Andhra Pradesh
2            Tamil Nadu
3        Andhra Pradesh
4        Andhra Pradesh
              ...
40195         Karnataka
40196       Maharashtra
40197         Telangana
40198    Andhra Pradesh
40199       Maharashtra
Name: State, Length: 40200, dtype: object

In [40]:
ecommerce["State"].isnull().sum()

np.int64(0)

## 12. Clean Customer_ID Fill missing values with mode.

In [41]:
ecommerce["Customer_ID"].isnull().sum()

np.int64(80)

In [42]:
ecommerce["Customer_ID"].mode()

0    CUST00547
Name: Customer_ID, dtype: object

In [43]:
ecommerce["Customer_ID"] = ecommerce["Customer_ID"].fillna(ecommerce["Customer_ID"].mode()[0])
ecommerce["Customer_ID"]

0        CUST03038
1        CUST05160
2        CUST05005
3        CUST06475
4        CUST05030
           ...
40195    CUST05074
40196    CUST01315
40197    CUST05479
40198    CUST04318
40199    CUST00972
Name: Customer_ID, Length: 40200, dtype: object

In [44]:
ecommerce["Customer_ID"].isnull().sum()

np.int64(0)

## 13. Final CheckConfirm the dataset is fully cleaned - no missing values, correct data types.

In [45]:
ecommerce.isnull().sum()

Order_ID        0
Order_Date      0
Customer_ID     0
Product_Name    0
Category        0
Sub_Category    0
Quantity        0
Sales           0
Discount        0
Profit          0
City            0
State           0
Payment_Mode    0
dtype: int64

In [46]:
ecommerce.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40200 entries, 0 to 40199
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order_ID      40200 non-null  object
 1   Order_Date    40200 non-null  datetime64[ns]
 2   Customer_ID   40200 non-null  object
 3   Product_Name  40200 non-null  object
 4   Category      40200 non-null  object
 5   Sub_Category  40200 non-null  object
 6   Quantity      40200 non-null  float64
 7   Sales         40200 non-null  float64
 8   Discount      40200 non-null  int64
 9   Profit        40200 non-null  float64
 10  City          40200 non-null  object
 11  State         40200 non-null  object
 12  Payment_Mode  40200 non-null  object
dtypes: datetime64[ns](1), float64(3), int64(1), object(8)
memory usage: 4.0+ MB

## 14. Save Cleaned Dataset

In [47]:
ecommerce.to_csv("ecommerce_cleaned.csv", index=False)